### ISSUE TITLE
Magisk breaking fingerprint navigation

### ISSUE THREAD

**Issue by krux3r** [ianmacd/MagiskBuilds#1]
Hey.

First of all sorry to get to you like this, I wanted to ask @topjohnwu but didn't know how to get to him.

So, I've been having problems on Huawei P10 Lite running a treble rom.

So, the issue is after installing huawei camera magisk module, fingeprint sensor starts acting weirdly.

Treble developer told me to tell the magisk dev about this and I should send him this: https://github.com/phhusson/device_phh_treble/blob/android-8.1/rw-system.sh#L53

I hope that will help somehow.

Thanks in advance!

**Comment by osly888** [comment]
If the problem only occurs after flashing the module, then it's the module's problem. Not ianmacd's or topjohnwu's. You should talk to the one who made the module, and don't ask this question here.

**Comment by Dil3mm4** [comment]
You should get less salty @osly888. 
I guess you don't even know what the issue it's about, so I'd rather hearing from someone that can give a professional response other than bullshitting. 
Thanks for your understanding. 

I'm the developer of the module, and what's reported by @krux3r it's what it happens. 
With modules injecting stuff in under /system path the set +e gets broken and thus weird stuff happens.

**Comment by osly888** [comment]
Sorry, @Dil3mm4. I got a bit salty.
