### ISSUE TITLE
New randomise package name

### ISSUE THREAD

**Issue by MikuDroid** [ianmacd/MagiskBuilds#18]
Hi! sorry for asking you here since i don't know where should i ask for some help. Does this magisk build still using the same method of randomising package name? If yes, can you made a new randomise package name? Because [Grab Driver app](https://play.google.com/store/apps/details?id=com.grabtaxi.driver2) has been detecting magisk since forever, I suspect this has something to do with detecting package name. Why? because when the magisk zip is not installed, just installing the manager app (also hidden) is enough for triggering the root detection. 
[I also opened issue on topjohnwu's repo but sadly it's closed](https://github.com/topjohnwu/Magisk/issues/1661)
I hope you can help, thanks!

**Comment by heyfachri** [comment]
Magisk canary channel used to able to hide it but not long after Grab Driver update (I forgot which version) it seems fails again. I guess the only way is to either decompile & recompile Grab Driver app or to rename Magisk Manager app. Both option is out of my league.

**Comment by MikuDroid** [comment]
> Magisk canary channel used to able to hide it but not long after Grab Driver update (I forgot which version) it seems fails again. I guess the only way is to either decompile & recompile Grab Driver app or to rename Magisk Manager app. Both option is out of my league.

I tried to rename manager using apk cloner (renaming the package right?) But it's stopped working. Yeah, I can't do both options.

**Comment by heyfachri** [comment]
Have you tried this? https://github.com/Ingan121/UDSBypass 

I'm not sure if it works with Grab Driver but at least it works with Rootbeerfresh passed the UDS.

**Comment by MikuDroid** [comment]
> Have you tried this? https://github.com/Ingan121/UDSBypass
> 
> I'm not sure if it works with Grab Driver but at least it works with Rootbeerfresh passed the UDS.
This magisk build passed UDS check on rootbeerfresh, so I'm sure this is not the issue.
