### ISSUE TITLE
Magisk 17.1

### ISSUE THREAD

**Issue by manofsteel2017** [ianmacd/MagiskBuilds#2]
Support for the latest?
This seem to fix treble issue?

**Comment by manofsteel2017** [comment]
my playstore isn't certified 
not on pie 
magisk isn't working properly

**Comment by osly888** [comment]
That's weird. Does the official build of Magisk have this issue too?

**Comment by manofsteel2017** [comment]
yeah sadly

**Comment by osly888** [comment]
Then I think it's a ROM-side issue.
